# Configuration file
# key = value
quarkus.ssl.native=true

# Bluesky API configuration
quarkus.rest-client.bluesky-api.url=https://bsky.social
quarkus.rest-client.bluesky-api.scope=javax.inject.Singleton
