package fr.hardcoding;

import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.enterprise.context.ApplicationScoped;
import org.eclipse.microprofile.config.inject.ConfigProperty;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Mock implementation of BlueskyClient that returns pre-recorded responses from mock files.
 * This allows testing and UI development without requiring real Bluesky credentials.
 * 
 * Mock files are loaded from external file paths specified in properties, defaulting to
 * src/test/resources/bluesky-mocks/ to avoid duplication and allow direct use of files
 * generated by the mock generator.
 */
@ApplicationScoped
public class MockBlueskyClient implements BlueskyClient {
    private static final Logger LOGGER = Logger.getLogger(MockBlueskyClient.class.getName());
    private static final ObjectMapper mapper = new ObjectMapper();
    
    @ConfigProperty(name = "bluesky.mock.enabled", defaultValue = "false")
    boolean mockEnabled;
    
    @ConfigProperty(name = "bluesky.mock.session.file", defaultValue = "src/test/resources/bluesky-mocks/create-session-response.json")
    String sessionMockFile;
    
    @ConfigProperty(name = "bluesky.mock.search.file", defaultValue = "src/test/resources/bluesky-mocks/search-response-with-images.json")
    String searchMockFile;

    @Override
    public SessionResponse createSession(SessionRequest request) {
        if (!mockEnabled) {
            throw new UnsupportedOperationException("Mock client should only be called when mock mode is enabled");
        }
        
        LOGGER.info("MockBlueskyClient: Returning mock session response from: " + sessionMockFile);
        try {
            return loadMockFromFile(sessionMockFile, SessionResponse.class);
        } catch (IOException e) {
            LOGGER.log(Level.SEVERE, "Failed to load mock session response from: " + sessionMockFile, e);
            throw new RuntimeException("Failed to load mock session response", e);
        }
    }

    @Override
    public SearchResponse searchPosts(String authorization, String query, Integer limit, String cursor) {
        if (!mockEnabled) {
            throw new UnsupportedOperationException("Mock client should only be called when mock mode is enabled");
        }
        
        LOGGER.info(String.format("MockBlueskyClient: Returning mock search response for query: %s from: %s", query, searchMockFile));
        try {
            return loadMockFromFile(searchMockFile, SearchResponse.class);
        } catch (IOException e) {
            LOGGER.log(Level.SEVERE, "Failed to load mock search response from: " + searchMockFile, e);
            throw new RuntimeException("Failed to load mock search response", e);
        }
    }

    private <T> T loadMockFromFile(String filePath, Class<T> responseClass) throws IOException {
        File file = new File(filePath);
        if (!file.exists()) {
            throw new IOException("Mock file not found: " + filePath);
        }
        
        try (InputStream is = new FileInputStream(file)) {
            return mapper.readValue(is, responseClass);
        }
    }
}
